autoformation_user:
    resource: "@AutoformationUserBundle/Resources/config/routing.yml"
    prefix:   /

autoformation_blog:
    resource: "@AutoformationBlogBundle/Resources/config/routing.yml"
    prefix:   /Blog

app:
    resource: @AppBundle/Controller/
    type:     annotation
