security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
    role_hierarchy:
        ROLE_ADMINISTRATEUR:       ROLE_UTILISATEUR
        ROLE_SUPER_ADMINISTRATEUR: [ROLE_UTILISATEUR, ROLE_ADMINISTRATEUR]
    providers:
        in_memory:
            memory:
                users:
                    oumar:    { password: konate, roles: ['ROLE_UTILISATEUR'] }
                    admin:    { password: admin, roles: ['ROLE_ADMINISTRATEUR'] }

    firewalls:
        main_login:
            pattern: ^/Blog/login$
            anonymous: true
        main:
            pattern:   ^/
            anonymous: false
            provider:  in_memory
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /Blog
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
    access_control:
        - {path: ^/ajouter, roles: ROLE_ADMINISTRATEUR}